### ISSUE TITLE
[Epic] Dynamic Permission Scanning

### ISSUE THREAD

**Issue by nathanbrophy** [IBM/operator-permission-advisor#2]
# Background

It can be hard to understand what permissions are needed in an install of an Operator or an Operand.  It would be nice if a tool existed that allowed you to dynamically scan a cluster and then write a report of the permissions used during that scan for a given actor. 

# Design

```
$ opa dynamic -a admin -a 'system:serviceaccount:test-namespace:my-operator' -d 5m # default is -1 ^C tp exit
```

This could be implemented as a webhook plugin to the admission control plane.  The idea would be to intercept any API call to the Kube API server that originates from one of the specified `actors`, record the API request and infer the permissions from it.  

e.x.:

```
GET pods # Needs get, list
GET pod/my-pod # Needs get
POST pod/my-pod data..... # Needs create 
etc ......
```

# Acceptance Criteria

- [ ] e2e test suite updated/created for the dynamic scan functionality 
- [ ] command that allows dynamic scanning of a cluster 
- [ ] audit report generated for permissions requested during the scan 
- [ ] aggregator to generate a `role` and/or `clusterRole` from the audit report
